-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 23:14:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mascotasalud
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mascotasalud` ;

-- -----------------------------------------------------
-- Schema mascotasalud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mascotasalud` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mascotasalud` ;

-- -----------------------------------------------------
-- Table `mascotasalud`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mascotasalud`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mascotasalud`.`usuario` (
  `UUID` VARCHAR(36) NOT NULL DEFAULT uuid(),
  `email` VARCHAR(45) NOT NULL,
  `password_hash` TEXT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nac` DATE NULL DEFAULT NULL,
  `empleo` VARCHAR(45) NULL DEFAULT NULL,
  `foto` TEXT NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`UUID`),
  UNIQUE INDEX `UUID_UNIQUE` (`UUID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mascotasalud`.`mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mascotasalud`.`mascota` ;

CREATE TABLE IF NOT EXISTS `mascotasalud`.`mascota` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `n_chip` INT NULL DEFAULT NULL,
  `fecha_nac` DATE NULL DEFAULT NULL,
  `foto` TEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `raza` VARCHAR(45) NULL DEFAULT NULL,
  `genero` ENUM('M', 'H') NULL DEFAULT NULL,
  `vacuna_basica` TINYINT NULL DEFAULT NULL,
  `UUID_usuario` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `n_chip_UNIQUE` (`n_chip` ASC) VISIBLE,
  INDEX `UUID_usuario_fk_idx` (`UUID_usuario` ASC) VISIBLE,
  CONSTRAINT `UUID_usuario_mascota_fk`
    FOREIGN KEY (`UUID_usuario`)
    REFERENCES `mascotasalud`.`usuario` (`UUID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mascotasalud`.`gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mascotasalud`.`gasto` ;

CREATE TABLE IF NOT EXISTS `mascotasalud`.`gasto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `UUID_usuario` VARCHAR(36) NOT NULL,
  `ID_mascota` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `UUID_ususario_fk_idx` (`UUID_usuario` ASC) VISIBLE,
  INDEX `ID_mascota_fk_idx` (`ID_mascota` ASC) VISIBLE,
  CONSTRAINT `ID_mascota_gasto_fk`
    FOREIGN KEY (`ID_mascota`)
    REFERENCES `mascotasalud`.`mascota` (`ID`),
  CONSTRAINT `UUID_usuario_gasto_fk`
    FOREIGN KEY (`UUID_usuario`)
    REFERENCES `mascotasalud`.`usuario` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mascotasalud`.`historial_mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mascotasalud`.`historial_mascota` ;

CREATE TABLE IF NOT EXISTS `mascotasalud`.`historial_mascota` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `peso` FLOAT NULL DEFAULT NULL,
  `antiparasitario` TINYINT(1) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `ID_mascota` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `ID_mascota_fk_idx` (`ID_mascota` ASC) VISIBLE,
  CONSTRAINT `ID_mascota_fk`
    FOREIGN KEY (`ID_mascota`)
    REFERENCES `mascotasalud`.`mascota` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
